/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef OS_LINUX
#include <jni.h>
#else
#include "./include/jni.h"
#endif
/* Header for class ICTCLAS_I3S_AC_ICTCLAS50 */

#ifndef _Included_ICTCLAS_I3S_AC_ICTCLAS50
#define _Included_ICTCLAS_I3S_AC_ICTCLAS50
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_Init
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1Init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_Exit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1Exit
  (JNIEnv *, jobject);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_ImportUserDictFile
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1ImportUserDictFile
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_SaveTheUsrDic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1SaveTheUsrDic
  (JNIEnv *, jobject);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_SetPOSmap
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1SetPOSmap
  (JNIEnv *, jobject, jint);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_FileProcess
 * Signature: ([BII[B)Z
 */
JNIEXPORT jboolean JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1FileProcess
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    ICTCLAS_ParagraphProcess
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_ICTCLAS_1ParagraphProcess
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ICTCLAS_I3S_AC_ICTCLAS50
 * Method:    nativeProcAPara
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ICTCLAS_I3S_AC_ICTCLAS50_nativeProcAPara
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
